
INSERT INTO genero (descricao) VALUES ('Acao');
INSERT INTO genero (descricao) VALUES ('Animacao');
INSERT INTO genero (descricao) VALUES ('Aventura');
INSERT INTO genero (descricao) VALUES ('Cinema de arte');
INSERT INTO genero (descricao) VALUES ('Chanchada');
INSERT INTO genero (descricao) VALUES ('Cinema catastrofe');
INSERT INTO genero (descricao) VALUES ('Comedia');
INSERT INTO genero (descricao) VALUES ('Comedia romantica');
INSERT INTO genero (descricao) VALUES ('Comedia dramatica');
INSERT INTO genero (descricao) VALUES ('Comedia de acao');
INSERT INTO genero (descricao) VALUES ('Cult');
INSERT INTO genero (descricao) VALUES ('Danca');
INSERT INTO genero (descricao) VALUES ('Documentario');
INSERT INTO genero (descricao) VALUES ('Docuficcao');
INSERT INTO genero (descricao) VALUES ('Drama');
INSERT INTO genero (descricao) VALUES ('Espionagem');
INSERT INTO genero (descricao) VALUES ('Ficcao cientifica');
INSERT INTO genero (descricao) VALUES ('Musical');
INSERT INTO genero (descricao) VALUES ('Policial');
INSERT INTO genero (descricao) VALUES ('Romance');
INSERT INTO genero (descricao) VALUES ('Suspense');
INSERT INTO genero (descricao) VALUES ('Terror');

INSERT INTO cidade (nome) VALUES ('Pato Branco');
INSERT INTO cidade (nome) VALUES ('Curitiba');
INSERT INTO cidade (nome) VALUES ('Sao Paulo');
INSERT INTO cidade (nome) VALUES ('Patos de Minas');
INSERT INTO cidade (nome) VALUES ('Nova York');
INSERT INTO cidade (nome) VALUES ('Roma');
INSERT INTO cidade (nome) VALUES ('YokishiCity');
INSERT INTO cidade (nome) VALUES ('New Orleans');
INSERT INTO cidade (nome) VALUES ('Tokyo');
INSERT INTO cidade (nome) VALUES ('Kyoto');
INSERT INTO cidade (nome) VALUES ('Beltrão');
INSERT INTO cidade (nome) VALUES ('Dois Vizinhos');
INSERT INTO cidade (nome) VALUES ('Berlin');
INSERT INTO cidade (nome) VALUES ('Buenos Aires');

INSERT INTO editora (nome) VALUES ('AMC');
INSERT INTO editora (nome) VALUES ('HBO');
INSERT INTO editora (nome) VALUES ('CBS');
INSERT INTO editora (nome) VALUES ('BBC');
INSERT INTO editora (nome) VALUES ('Sony');
INSERT INTO editora (nome) VALUES ('Fox');
INSERT INTO editora (nome) VALUES ('Disney');
INSERT INTO editora (nome) VALUES ('NBC Universal');
INSERT INTO editora (nome) VALUES ('Warner Bros');
INSERT INTO editora (nome) VALUES ('ABC');
INSERT INTO editora (nome) VALUES ('Netflix');
INSERT INTO editora (nome) VALUES ('Amazon');
INSERT INTO editora (nome) VALUES ('FX Productions');
INSERT INTO editora (nome) VALUES ('Paramount');

INSERT INTO autor (nome) VALUES ('Luciano Hulk');
INSERT INTO autor (nome) VALUES ('Bolsonaro');
INSERT INTO autor (nome) VALUES ('Chris');
INSERT INTO autor (nome) VALUES ('ErickCartman');
INSERT INTO autor (nome) VALUES ('Gisly');
INSERT INTO autor (nome) VALUES ('Samantha');
INSERT INTO autor (nome) VALUES ('RobsonBrabo');
INSERT INTO autor (nome) VALUES ('Rafaeru');
INSERT INTO autor (nome) VALUES ('Italozera');
INSERT INTO autor (nome) VALUES ('XandimDaMassa');
INSERT INTO autor (nome) VALUES ('Vitinzera');
INSERT INTO autor (nome) VALUES ('Marcelin');
INSERT INTO autor (nome) VALUES ('Pancadao');
INSERT INTO autor (nome) VALUES ('Surface');

--INSERT INTO livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor)

insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Saving Face', 10, 8, 5, 2008, '84dm59ppit5jnyqqho3z', 4, 10.39);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Gruffalo, The', 8, 19, 10, 2007, 'h36z3r6xscvjrxg4z2sa', 9, 54.55);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('In Cold Blood', 4, 5, 3, 1991, '0dz0ctuwxm5jesif2419', 11, 362.63);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('War Wagon, The', 9, 21, 1, 2012, '7imym7kv8fju8qoksyyl', 11, 108.83);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Family Viewing', 5, 18, 12, 1993, 'efwsqsgcv5yeoyy5a3eb', 3, 229.65);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Thing Called Love, The', 6, 15, 2, 2017, 'hez4la84bnq6z7dq50wo', 7, 57.61);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Joy Ride', 6, 19, 12, 2009, 'oa2icyg2cjwm2ps5fequ', 13, 226.81);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Lost in La Mancha', 9, 12, 7, 1997, 'v1u3bljqarc78ywn11wm', 6, 275.75);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Bill Bailey: Tinselworm', 2, 19, 2, 1996, 'nvnwtr9gewlft8g6h7he', 13, 219.89);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Cannibal Women in the Avocado Jungle of Death', 11, 6, 8, 2017, 'hnyjn71dlmh2otta8b6k', 1, 195.31);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('H.H. Holmes: America''s First Serial Killer', 12, 11, 12, 2008, '9dbyjklkv4xtxegufubz', 14, 266.66);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Beastly', 4, 15, 8, 2006, 'p63qvc4dpoj1ozyxno36', 10, 187.34);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Fearless', 11, 4, 14, 2010, '8w6nna1s1k3dlzae1y0r', 9, 41.53);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Westward the Women', 14, 7, 1, 2015, 'd57ewypdhdkvn2p1a0zw', 6, 107.07);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Never Say... Never! (Il ne faut jurer... de rien!)', 7, 8, 14, 2003, '9ujyymvla2gllvgfbv1p', 2, 289.45);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Black Rain', 1, 10, 3, 2007, '00s2a250pwqwgz85coi2', 2, 59.17);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Men in War', 14, 18, 2, 2005, '0xo6f9ozxix2jdqzgzwx', 4, 407.73);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Shaolin Temple 2: Kids from Shaolin (Shao Lin xiao zi) (Kids from Shaolin)', 6, 10, 4, 2012, 'fd8fbx6j8js9o0uwmmtu', 3, 53.78);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('200 Cigarettes', 3, 15, 10, 2017, 'ut8b5zbijyszn6ovt5wp', 4, 275.53);
insert into livro (titulo, editora_id, genero_id, autor_id, ano, isbn, cidade_id, valor) values ('Brazilian Western (Faroeste Caboclo)', 8, 15, 2, 2007, '6lf6qpf7e9dcabhysdwc', 14, 248.98);
